// Original file: protos/portfoliopilotrpc/portfolio_pilot.proto

export const RejectCode = {
  REJECT_CODE_UNSPECIFIED: 'REJECT_CODE_UNSPECIFIED',
  REJECT_CODE_PRICE_ORACLE_UNAVAILABLE: 'REJECT_CODE_PRICE_ORACLE_UNAVAILABLE',
  REJECT_CODE_MIN_FILL_NOT_MET: 'REJECT_CODE_MIN_FILL_NOT_MET',
  REJECT_CODE_PRICE_BOUND_MISS: 'REJECT_CODE_PRICE_BOUND_MISS',
  REJECT_CODE_FOK_NOT_VIABLE: 'REJECT_CODE_FOK_NOT_VIABLE',
  REJECT_CODE_FILL_EXCEEDS_MAX: 'REJECT_CODE_FILL_EXCEEDS_MAX',
} as const;

export type RejectCodePartial =
  | 'REJECT_CODE_UNSPECIFIED'
  | 0
  | 'REJECT_CODE_PRICE_ORACLE_UNAVAILABLE'
  | 1
  | 'REJECT_CODE_MIN_FILL_NOT_MET'
  | 2
  | 'REJECT_CODE_PRICE_BOUND_MISS'
  | 3
  | 'REJECT_CODE_FOK_NOT_VIABLE'
  | 4
  | 'REJECT_CODE_FILL_EXCEEDS_MAX'
  | 5

export type RejectCode = typeof RejectCode[keyof typeof RejectCode]
